spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
