FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app


COPY ./shared-files-module /app/shared-files-module


WORKDIR /app/shared-files-module
RUN mvn clean install -DskipTests


WORKDIR /app/eureka
COPY ./eureka .


RUN mvn clean package -DskipTests


FROM eclipse-temurin:21-jre
WORKDIR /app


COPY --from=build /app/eureka/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]